spring:
  application:
    name: semanasanta-eventos

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  datasource:
    url: jdbc:postgresql://localhost:5432/semanasantaeventos
    username: postgres
    password: postgres

server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka